### ISSUE TITLE
对你的简历很感兴趣，有兴趣联系一下么

### ISSUE THREAD

**Issue by rainx** [razor1895/resume#1]
在GitHub上看到你的简历，我们目前正在招聘前端开发的职位，我已经在Github上添加你了，有机会沟通一下吧

**Comment by rainx** [comment]
我们的招聘信息 https://join.rightcapital.com/

**Comment by razor1895** [comment]
怎么联系呢？

**Comment by rainx** [comment]
可以在github上加我，我们pm

**Comment by rainx** [comment]
@razor1895

**Comment by rainx** [comment]
@razor1895 或者加我的微信 rainx1982 

> 怎么联系呢？
